feat: add `into_id` methods to all menu item types
amrbashir/menu-rs pull request #112
Opened 2023-08-31 13:39 UTC by rhysd

Fixes #111

This PR implements `into_id` methods to `MenuItem`, `CheckMenuItem`, `PredefinedMenuItem`, and `Submenu`. It moves the menu item into its menu ID.

Since I'm not understanding the policy to add a new method to traits, I'm not sure `into_id` method should be added to `IsMenuItem` trait. If it should not, please let me know. I'll update this branch to move the trait methods to normal methods.

2023-08-31 15:00 UTC, amrbashir requested changes

2023-08-31 15:00 UTC, amrbashir commented on src/lib.rs
> +    fn into_id(self) -> MenuId;
It is fine to add this to `IsMenuItem` trait but the trait is meant for internal usages only, so you also need to add it to each struct and also add it to `MenuItemKind` enum

2023-08-31 15:00 UTC, amrbashir commented on src/items/check.rs
> +}
move these tests to `src/items/mod.rs`

2023-08-31 16:51 UTC, rhysd commented
Thank you for the review. I will handle them tomorrow.

2023-08-31 19:15 UTC, amrbashir commented on src/lib.rs
> +    fn into_id(self) -> MenuId;
Actually, since there isn't any usage for it internally, it is useless to add it here

2023-09-01 09:34 UTC, rhysd commented
@amrbashir I fixed your review comments at 111e8a9

- Smaller trait is better. Since `into_id` was unnecessary for any implementation, I removed the method from the `IsMenuItem` trait
- Moved all `into_id` trait methods to each structs
- Added `MenuItemKind::into_id` method
- Gathered all tests into a single test case at `src/items/mod.rs`

2023-09-01 11:43 UTC, amrbashir approved these changes

2023-09-01 11:59 UTC, merged