chore: fix links in API document and add document link to README.md
amrbashir/menu-rs pull request #118
Opened 2023-09-05 14:02 UTC by rhysd

This PR fixes some links in API document. And it adds link to the documentation page in README since I wanted it while I was writing code with this library.

2023-09-05 14:18 UTC, amrbashir approved these changes

2023-09-05 14:21 UTC, amrbashir requested changes

2023-09-05 14:21 UTC, amrbashir commented on README.md
> +## Documentation
Actually, could we replace this with a badge from https://shields.io/badges/docs-rs at the top?

2023-09-07 14:38 UTC, rhysd commented
@amrbashir Thanks for the point. I replaced the document section with a badge.

2023-09-07 14:40 UTC, amrbashir approved these changes

2023-09-07 14:40 UTC, merged