Fixes for context menu problems on Win32
amrbashir/menu-rs pull request #214
Opened 2024-08-17 14:30 UTC by npwoods

These changes are to address a design flaw in how `muda` handles context menus on Windows.

The normal way menus with `muda` are used on Windows is they get attached to a window, and the window is subclassed to intercept commands (`WM_COMMAND`) and some drawing behaviors (I'm not 100% sure on this, but this appears in place to support theming and dark mode).  When the `Menu` is dropped, it will be unattached from all windows and the subclasses will be removed.

Context menus seem to follow a slightly different pattern.  When `show_context_menu_for_hwnd()` is called, the subclass is attached to the window, but never removed.  This behavior is problematic because the menu can be dropped without the subclass removed, causing a crash.  Furthermore, having this subclass attached unnecessarily is not necessarily a good idea.

These changes to `muda` refactor menu support on Windows to ensure that the subclass (which seems to be necessary to support theming) lives only while the context menu is active, which should address these problems.

These changes also address a memory leak where when an HWND is subclassed, the reference to the menu object was placed in a `Box` seemingly unnecessarily, and this `Box` never seems to be dropped.  This was changed to using straight references.

2024-08-21 21:34 UTC, amrbashir requested changes
Thank you, just a few comments and this should be good to go. 

Could you also add a change file in `.changes` directory?

2024-08-21 21:34 UTC, amrbashir commented on src/platform_impl/windows/mod.rs
> +        }
Not needed, we can remove this and `SetWindowSubclass` before calling `show_context_menu`.

2024-08-21 21:34 UTC, amrbashir commented on src/platform_impl/windows/mod.rs
> +                CONTEXT_SUBMENU_SUBCLASS_ID,
same here

2024-08-22 11:58 UTC, npwoods commented
I am interpreting your feedback as "'Now that the subclass doesn't handle `WM_COMMAND` for context menus, we can stop subclassing context menus'".  I'm surprised to hear this, as I thought that the subclass was still necessary for dark mode.  100% your call of course!

In any case, I've submitted my changes.  If there is anything else I need to do, let me know!

2024-08-22 14:16 UTC, amrbashir commented
> I am interpreting your feedback as "'Now that the subclass doesn't handle `WM_COMMAND` for context menus, we can stop subclassing context menus'".

Yeah that's what I meant exactly

> I'm surprised to hear this, as I thought that the subclass was still necessary for dark mode. 100% your call of course!

The subclass only draws the menu bar (the strip on top of the hwnd), context menus and also submenus from the menu bar are not drawn by us in dark mode.

2024-08-22 14:19 UTC, amrbashir commented on .changes/win32-context-menu-fixes
> +These changes also address a memory leak where when an HWND is subclassed, the reference to the menu object was placed in a `Box` seemingly unnecessarily, and this `Box` never seems to be dropped.  T
This is too much information for a changelog entry, it should be something simple like 

```suggestion
On Windows, fix crash when showing a context menu but dropping the Menu before the context menu is closed.
```

2024-08-22 14:23 UTC, amrbashir approved these changes

2024-08-22 14:30 UTC, merged

2024-08-22 14:31 UTC, amrbashir commented
Thank you

2024-08-22 16:00 UTC, npwoods commented
Thank you for all your help, and helping me muddle through the details!