feat(context-menu): returns context menu dismiss result
amrbashir/menu-rs pull request #236
Opened 2024-10-25 05:39 UTC by pewsheen

- Adding context menu dismiss result, so we would know the menu is dismissed because the user selected an item or canceled it.
- In this PR, it is only implemented on Mac and Windows.

2024-10-28 16:16 UTC, amrbashir requested changes
Can't we implement the same on Linux using the signals emitted on menus? 
see https://docs.gtk.org/gtk3/signal.MenuShell.selection-done.html and https://docs.gtk.org/gtk3/signal.MenuShell.cancel.html

2024-10-28 16:16 UTC, amrbashir commented on .changes/add-context-menu-dismiss-result.md
> +On macOS and Windows, context menu returns it's dismissed result.
```suggestion
Return `bool` in `ContextMenu::show_context_menu_for_hwnd` on Windows and `ContextMenu::show_context_menu_for_nsview` on macOS to indicate why the context menu was closed.
```

2024-10-29 07:45 UTC, pewsheen commented
> Can't we implement the same on Linux using the signals emitted on menus? see https://docs.gtk.org/gtk3/signal.MenuShell.selection-done.html and https://docs.gtk.org/gtk3/signal.MenuShell.cancel.html

Hmm, I'm expecting that the result could return synchronously when it is dismissed. Signals seem unable to do it synchronously.
If we need to support Linux, maybe it should emit a dismiss `MenuEvent` on all platforms?

2024-10-29 07:48 UTC, amrbashir commented
we can probably use a channel to synchronously wait for a result, no?

2024-10-29 07:49 UTC, pewsheen commented
> we can probably use a channel to synchronously wait for a result, no?

Cool, I'll try it later

2024-10-29 07:49 UTC, amrbashir commented
thanks, you may also need to do something like this https://github.com/tauri-apps/wry/blob/1d63fa325327a02a0a8be9ee50ce1eb7a0e8e04f/src/webkitgtk/mod.rs#L874-L880 in case it is dead-locking

2024-11-01 09:49 UTC, pewsheen commented
> Can't we implement the same on Linux using the signals emitted on menus? see https://docs.gtk.org/gtk3/signal.MenuShell.selection-done.html and https://docs.gtk.org/gtk3/signal.MenuShell.cancel.html

Just added these two signals.
But the events are slightly not as expected that when I mouse click on an empty space. On macOS and Windows, they will see this behavior as canceled, but on Linux (at least on Wayland), it sees it as select-done

2024-11-05 02:08 UTC, amrbashir commented on src/lib.rs
> +    /// Returns `true` if menu tracking ended because an item was selected or clicked other place to dismiss the menu
```suggestion
    /// Returns `true` if menu tracking ended because an item was selected or clicked outside the menu to dismiss it.
```

2024-11-05 02:09 UTC, amrbashir commented on .changes/add-context-menu-dismiss-result.md
> +Return `bool` in `ContextMenu::show_context_menu_for_hwnd` on Windows and `ContextMenu::show_context_menu_for_nsview` on macOS to indicate why the context menu was closed.
```suggestion
---
"muda": minor
---

Return `bool` in `ContextMenu::show_context_menu_for_hwnd`, `ContextMenu::show_context_menu_for_nsview` and `ContextMenu::show_context_menu_for_gtk_window` to indicate why the context menu was closed.
```

2024-11-05 02:10 UTC, amrbashir approved these changes

2024-11-05 02:11 UTC, amrbashir approved these changes

2024-11-05 02:15 UTC, amrbashir commented on src/platform_impl/gtk/mod.rs
> +        let id2 = gtk_menu.connect_selection_done(move |s| tx.send(true).unwrap_or(()));
```suggestion
        let id2 = gtk_menu.connect_selection_done(move |_| tx.send(true).unwrap_or(()));
```

2024-11-05 02:15 UTC, amrbashir approved these changes

2024-11-05 02:21 UTC, merged